// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: filesService.proto

package service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for FileService service

func NewFileServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for FileService service

type FileService interface {
	CreateNewFileRoot(ctx context.Context, in *FileRequest, opts ...client.CallOption) (*FileResponse, error)
	GetFilesByParentDictId(ctx context.Context, in *FileRequest, opts ...client.CallOption) (*FileResponse, error)
	AddFile(ctx context.Context, in *FileRequest, opts ...client.CallOption) (*FileResponse, error)
	AddDict(ctx context.Context, in *FileRequest, opts ...client.CallOption) (*FileResponse, error)
	DeleteFile(ctx context.Context, in *FileRequest, opts ...client.CallOption) (*FileResponse, error)
	GetFile(ctx context.Context, in *FileRequest, opts ...client.CallOption) (*FileResponse, error)
}

type fileService struct {
	c    client.Client
	name string
}

func NewFileService(name string, c client.Client) FileService {
	return &fileService{
		c:    c,
		name: name,
	}
}

func (c *fileService) CreateNewFileRoot(ctx context.Context, in *FileRequest, opts ...client.CallOption) (*FileResponse, error) {
	req := c.c.NewRequest(c.name, "FileService.CreateNewFileRoot", in)
	out := new(FileResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileService) GetFilesByParentDictId(ctx context.Context, in *FileRequest, opts ...client.CallOption) (*FileResponse, error) {
	req := c.c.NewRequest(c.name, "FileService.GetFilesByParentDictId", in)
	out := new(FileResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileService) AddFile(ctx context.Context, in *FileRequest, opts ...client.CallOption) (*FileResponse, error) {
	req := c.c.NewRequest(c.name, "FileService.AddFile", in)
	out := new(FileResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileService) AddDict(ctx context.Context, in *FileRequest, opts ...client.CallOption) (*FileResponse, error) {
	req := c.c.NewRequest(c.name, "FileService.AddDict", in)
	out := new(FileResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileService) DeleteFile(ctx context.Context, in *FileRequest, opts ...client.CallOption) (*FileResponse, error) {
	req := c.c.NewRequest(c.name, "FileService.DeleteFile", in)
	out := new(FileResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileService) GetFile(ctx context.Context, in *FileRequest, opts ...client.CallOption) (*FileResponse, error) {
	req := c.c.NewRequest(c.name, "FileService.GetFile", in)
	out := new(FileResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FileService service

type FileServiceHandler interface {
	CreateNewFileRoot(context.Context, *FileRequest, *FileResponse) error
	GetFilesByParentDictId(context.Context, *FileRequest, *FileResponse) error
	AddFile(context.Context, *FileRequest, *FileResponse) error
	AddDict(context.Context, *FileRequest, *FileResponse) error
	DeleteFile(context.Context, *FileRequest, *FileResponse) error
	GetFile(context.Context, *FileRequest, *FileResponse) error
}

func RegisterFileServiceHandler(s server.Server, hdlr FileServiceHandler, opts ...server.HandlerOption) error {
	type fileService interface {
		CreateNewFileRoot(ctx context.Context, in *FileRequest, out *FileResponse) error
		GetFilesByParentDictId(ctx context.Context, in *FileRequest, out *FileResponse) error
		AddFile(ctx context.Context, in *FileRequest, out *FileResponse) error
		AddDict(ctx context.Context, in *FileRequest, out *FileResponse) error
		DeleteFile(ctx context.Context, in *FileRequest, out *FileResponse) error
		GetFile(ctx context.Context, in *FileRequest, out *FileResponse) error
	}
	type FileService struct {
		fileService
	}
	h := &fileServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&FileService{h}, opts...))
}

type fileServiceHandler struct {
	FileServiceHandler
}

func (h *fileServiceHandler) CreateNewFileRoot(ctx context.Context, in *FileRequest, out *FileResponse) error {
	return h.FileServiceHandler.CreateNewFileRoot(ctx, in, out)
}

func (h *fileServiceHandler) GetFilesByParentDictId(ctx context.Context, in *FileRequest, out *FileResponse) error {
	return h.FileServiceHandler.GetFilesByParentDictId(ctx, in, out)
}

func (h *fileServiceHandler) AddFile(ctx context.Context, in *FileRequest, out *FileResponse) error {
	return h.FileServiceHandler.AddFile(ctx, in, out)
}

func (h *fileServiceHandler) AddDict(ctx context.Context, in *FileRequest, out *FileResponse) error {
	return h.FileServiceHandler.AddDict(ctx, in, out)
}

func (h *fileServiceHandler) DeleteFile(ctx context.Context, in *FileRequest, out *FileResponse) error {
	return h.FileServiceHandler.DeleteFile(ctx, in, out)
}

func (h *fileServiceHandler) GetFile(ctx context.Context, in *FileRequest, out *FileResponse) error {
	return h.FileServiceHandler.GetFile(ctx, in, out)
}
