// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.2
// source: userModel.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id"
	ID uint32 `protobuf:"varint,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	// @inject_tag: json:"username"
	Username string `protobuf:"bytes,2,opt,name=Username,json=username,proto3" json:"Username,omitempty"`
	// @inject_tag: json:"email"
	Email string `protobuf:"bytes,3,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	// @inject_tag: json:"client_random_value"
	ClientRandomValue string `protobuf:"bytes,4,opt,name=ClientRandomValue,json=client_random_value,proto3" json:"ClientRandomValue,omitempty"`
	// @inject_tag: json:"encrypted_master_key"
	EncryptedMasterKey string `protobuf:"bytes,5,opt,name=EncryptedMasterKey,json=encrypted_master_key,proto3" json:"EncryptedMasterKey,omitempty"`
	// @inject_tag: json:"hashed_authentication_key"
	HashedAuthenticationKey string `protobuf:"bytes,6,opt,name=HashedAuthenticationKey,json=hashed_authentication_key,proto3" json:"HashedAuthenticationKey,omitempty"`
	// @inject_tag: json:"regdate"
	Regdate string `protobuf:"bytes,7,opt,name=Regdate,json=reg_date,proto3" json:"Regdate,omitempty"`
	// @inject_tag: json:"logins"
	Logins int64 `protobuf:"varint,8,opt,name=Logins,proto3" json:"Logins,omitempty"`
	// @inject_tag: json:"root_dict_id"
	RootDictId int64 `protobuf:"varint,9,opt,name=RootDictId,json=root_dict_id,proto3" json:"RootDictId,omitempty"`
}

func (x *UserModel) Reset() {
	*x = UserModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userModel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserModel) ProtoMessage() {}

func (x *UserModel) ProtoReflect() protoreflect.Message {
	mi := &file_userModel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserModel.ProtoReflect.Descriptor instead.
func (*UserModel) Descriptor() ([]byte, []int) {
	return file_userModel_proto_rawDescGZIP(), []int{0}
}

func (x *UserModel) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *UserModel) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserModel) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserModel) GetClientRandomValue() string {
	if x != nil {
		return x.ClientRandomValue
	}
	return ""
}

func (x *UserModel) GetEncryptedMasterKey() string {
	if x != nil {
		return x.EncryptedMasterKey
	}
	return ""
}

func (x *UserModel) GetHashedAuthenticationKey() string {
	if x != nil {
		return x.HashedAuthenticationKey
	}
	return ""
}

func (x *UserModel) GetRegdate() string {
	if x != nil {
		return x.Regdate
	}
	return ""
}

func (x *UserModel) GetLogins() int64 {
	if x != nil {
		return x.Logins
	}
	return 0
}

func (x *UserModel) GetRootDictId() int64 {
	if x != nil {
		return x.RootDictId
	}
	return 0
}

var File_userModel_proto protoreflect.FileDescriptor

var file_userModel_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0xc0, 0x02, 0x0a, 0x09,
	0x55, 0x73, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x2e, 0x0a, 0x11, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x72,
	0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x30, 0x0a, 0x12, 0x45,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x4b, 0x65,
	0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x65, 0x64, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x6b, 0x65, 0x79, 0x12, 0x3a, 0x0a,
	0x17, 0x48, 0x61, 0x73, 0x68, 0x65, 0x64, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x19,
	0x68, 0x61, 0x73, 0x68, 0x65, 0x64, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x12, 0x19, 0x0a, 0x07, 0x52, 0x65, 0x67,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x67, 0x5f,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x73, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x73, 0x12, 0x20, 0x0a, 0x0a,
	0x52, 0x6f, 0x6f, 0x74, 0x44, 0x69, 0x63, 0x74, 0x49, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x64, 0x69, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x42, 0x0b,
	0x5a, 0x09, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_userModel_proto_rawDescOnce sync.Once
	file_userModel_proto_rawDescData = file_userModel_proto_rawDesc
)

func file_userModel_proto_rawDescGZIP() []byte {
	file_userModel_proto_rawDescOnce.Do(func() {
		file_userModel_proto_rawDescData = protoimpl.X.CompressGZIP(file_userModel_proto_rawDescData)
	})
	return file_userModel_proto_rawDescData
}

var file_userModel_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_userModel_proto_goTypes = []interface{}{
	(*UserModel)(nil), // 0: services.UserModel
}
var file_userModel_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_userModel_proto_init() }
func file_userModel_proto_init() {
	if File_userModel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_userModel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_userModel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_userModel_proto_goTypes,
		DependencyIndexes: file_userModel_proto_depIdxs,
		MessageInfos:      file_userModel_proto_msgTypes,
	}.Build()
	File_userModel_proto = out.File
	file_userModel_proto_rawDesc = nil
	file_userModel_proto_goTypes = nil
	file_userModel_proto_depIdxs = nil
}
